import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "../layouts/navBar/index";
import LeftBody from "../layouts/leftBody/index";
import Footer from "../layouts/footer/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Synk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <NavBar />
        </header>
        <div className="content__wrapper">
          <LeftBody />
          {children}
        </div>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
